- name: Ping Windows hosts
  hosts: all
  tasks:

    - name: Run PowerShell command
      win_shell: |
        Get-Service
      register: powershell_output

    - name: Print PowerShell command output
      debug:
        msg: "{{ powershell_output.stdout }}"
        
    - name: Ping Windows hosts
      win_shell: ipconfig

    - name: Ping Windows hosts1
      win_ping:
      
   - name: download file
     ansible.windows.win_get_url:
       url: "https://awscli.amazonaws.com/AWSCLIV2.msi"
       dest: "c:\\temp\\AWSCLIV2.msi"
