- name: Ping
  hosts: all
 
  tasks:
  - name: ping
    win_ping:

  - name: Get whoami information
    ansible.windows.win_whoami:

  - name: Get disk facts
    community.windows.win_disk_facts:

  - name: Add a PowerShell module  
    community.windows.win_psmodule:    
      name: SQLServerDsc    
      state: present
