- name: Ping
  hosts: all
 
  tasks:
  - name: ping
    win_ping:

  - name: Get whoami information
    ansible.windows.win_whoami:

  - name: Get info about all modules on the system
    community.windows.win_psmodule_info: