- name: Ping
  hosts: all
 
  tasks:
  - name: ping
    ansible.windows.win_ping:

  - name: Get whoami information
    ansible.windows.win_whoami:

  - name: Run multi-lined shell commands
    ansible.windows.win_shell: |
         ipconfig

  - name: Remove dba tools
    community.windows.win_psmodule:
      name: dbatools
      state: absent

  - name: Get info about all modules on the system
    community.windows.win_psmodule_info:
